# -*- coding: utf-8 -*-
"""Takım - 9 YetCoffee

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_cYiVLuLGKea4wEuNJ4WIagr2K2fd_P
"""

import time
menu={
    "americano":20,
    "latte":25,
    "macchiatto":15,
    "espresso":10
}

print("Americano fiyatı:", menu["americano"])
print("Latte fiyatı:",menu["latte"])

def display_menu():
  print("-----YETCoffee MENU------")

  for item in list(menu.keys()):
    print(f"{item.upper():<10}:{menu[item]} TL")

class KahveMakinesi():
    def init( self,otomat_durumu="acik",kahve_listesi=["americano","latte","filtre kahve","espresso"],fiyat={
    "americano":20,
    "latte":25,
    "filtre kahve":15,
    "espresso":10
    
    }):
     self.otomat_durumu=otomat_durumu
     self.kahve_listesi=kahve_listesi
     self.fiyat=fiyat

    def otomat_ac(self):
        if self.otomat_durum=="Kapalı":
            print("Kahve makinesi açılıyor...")
        else:
            print("Kahve makinesi zaten açık.")

        def otomat_kapat(self):
            if self.otomat_durum=="Açık":
                print("Kahve makinesi kapanıyor...")
            else:
              print("Kahve makinesi kapanıyor...")

        def kahve_tercihi(self):
            veri=input("Lütfen listeden eklemek istediğiniz kahveyi seçiniz.")
            self.kahve_listesi.append(veri)
        def kahve_satin_alma(self):
            display_menu()
            print("Lütfen satın almak istediğiniz ürünü seçiniz.")

        def satin_alma():
            display_menu()
            print("Lütfen satın almak istediğiniz kahveyi giriniz. ")


        satin_alinan_urunler= []
        satin_alma_adedi= []

        son_fiyat= 0

        while 1 :
         eklenecek_urun=input("Hangi ürünü eklemek istersiniz?")
         
         if eklenecek_urun== "0":
           print("Fiş kaydediliyor.")
           break


         ekleme_adedi=int(input("Kaç adet ürün eklemek istiyorsunuz?"))
         fiyat= "tek_urun_hesaplama"(eklenecek_urun,ekleme_adedi)
         
         if fiyat is None:
           print("Yanlış bir giriş yaptınız,kahve seçmelisiniz.")

        else:
         print(f"Satın alma ücreti:{fiyat}.\nSatın almayı onaylamak için 'e' iptal etmek için 'h'giriniz.")
         check= input("Satın almayı onaylıyor musunuz?")
         if check== "e":
          print("Satın alma onaylandı.")
        print("-"*50)
        if check=="h":
         print("Satın alma işlemi iptal edildi.")
        print("-"*50)

        son_fiyat+= fiyat
        satin_alinan_urunler.append(eklenecek_urun)
        satin_alma_adedi.append(ekleme_adedi)
        print(f"Ara Toplam:{son_fiyat}")
      
        return son_fiyat,satin_alinan_urunler,satin_alma_adedi
          
        def makine_stogu():
            print(f"Bu makinede{su}ml su ,{sut}ml süt, {seker}g şeker ve {kahve}g kahve bulunmaktadır.")
            
            def makine_dolum():
              global su,sut,seker,kahve
              su_ml = int(input("Ne kadar su ekleyelim ?: "))
              sut_ml = int(input("Ne kadar süt ekleyelim ?: "))
              seker_g = int(input("Ne kadar şeker ekleyelim ?: "))
              kahve_g = int(input("Ne kadar kahve ekleyelim ?: "))
              su += su_ml
              sut += sut_ml
              seker += seker_g
              kahve+= kahve_g
              
              def yeterli_miktar(icecekAdi):
                 if icecekAdi == "latte":
                   return su >= 150 and sut >= 50 and seker >= 15 and kahve >= 5
                 elif icecekAdi=="espresso":
                   return su >= 200  and kahve >= 10
                 elif icecekAdi == "":
                  return sur >= 150 and sut >= 80 and seker >= 25 and kahve >= 8
            
            def kahve_yap(icecekAdi):
              global su, sut, seker, kahve
              if yeterli_miktar(icecekAdi):
                if icecekAdi == "latte":
                  su -= 150
                  sut -= 50
                  seker -= 15
                  kahve -= 5
                elif icecekAdi == "espresso":
                    su -= 100
                    kahve -= 10
                elif icecekAdi == "macchiatto":
                 su -= 150
                sut-= 80
                seker -= 20
                kahve -= 8
              elif icecekAdi == "americano":
               su-= 200
               kahve-=15
               print(f"Kahveniz {icecekAdi} hazır!, Afiyet Olsun!")
              else:
               print("Kahve yapmak için yeterli malzeme yok, Üzgünüz!")

    kahve_makinesi_acik=True

    su = 500
    sut = 300
    seker = 100
    kahve = 40

    kahve_listesi=["americano","latte","filtre kahve","espresso"]
    
    while kahve_makinesi_acik:

      secenek = input("Menüden içmek istediğiniz içeceği seçiniz.(Dolum yapmak için 'fill'yazınız.),(Çıkmak için 'exit'yazınız.) ")

      if "exit":
          print("Teşekkürler,Görüşmek üzere!")
          kahve_makinesi_acik = False
      elif secenek in kahve_listesi:
          "kahve_yap"(secenek)
      elif secenek == "fill":
        "makine_dolum"(secenek)
      else:
        print("Yeniden deneyiniz!")